### ISSUE TITLE
Update by Id

### ISSUE THREAD

**Issue by gamedolphin** [ostafen/clover#11]
Couldn't find a documented way of doing so.

**Comment by ostafen** [comment]
You are right. There is no method for this. I will add it. Thank you

**Comment by ostafen** [comment]
I correct myself. In section "Update and Delete documents" it is shown howto update documents matching a predefined criteria.

So you could simply achieve this by the following code:

```go
db.Query("dbname").Where(c.Field("_id").Eq(docId)).Update(updates)
```

where updates is your update map, and docId is the id of your document.
Probably, it's better to put this example in the README to give evidence that each document has an "_id" field

**Comment by gamedolphin** [comment]
Thank you for the clarification. Cheer!
