### ISSUE TITLE
Implement sorting

### ISSUE THREAD

**Issue by jsgm** [ostafen/clover#13]
Hello,

It would be a good idea to have the possibility of sorting the different FindAll() results.

In order to don't make the code complex, here are a few simple ideas for sorting results numerically and alphabetically that would be useful to implement:
db.Query("todos").Where(c.Field("completed").Eq(true).And(c.Field("userId").In(5, 8))).FindAll().SortAsc("userId") _and SortDesc_
db.Query("todos").Where(c.Field("completed").Eq(true).And(c.Field("userId").In(5, 8))).FindAll().Sort("userId", 1) _or -1_

**Comment by ostafen** [comment]
@jsgm: check 07c2f731a6e869f5fdec1bd5467b18054c58dcc8
Let me know what you think about the APIs (you can use function TestSort as a reference)
