### ISSUE TITLE
Memory store was removed in v2

### ISSUE THREAD

**Issue by daenney** [ostafen/clover#141]
Looking at the README, there's a line for `c.Open("", c.InMemory(true))` suggesting that there's a way to use Clover with memory-backed storage. I wanted to use this in tests. However, the import path there is for the original/v1 version of the package. Trying the same thing in v2, it seems this option is gone and `Open()` no longer accepts such options.

Digging into the store package a bit, there doesn't seem to be an in-memory option anymore either. Was this removed in v2? I assume that now the only option is to use Badger with their in-memory implementation?

**Comment by ostafen** [comment]
Yes, you're right
