### ISSUE TITLE
Plan about awesome warehouse

### ISSUE THREAD

**Issue by ASWLaunchs** [ostafen/clover#15]
It is recommended to create a new warehouse called **awesome-clover** or **awesome-cloverdb**.

CloverDB will have more people in the future, but the only program-self is not enough, although this database is a very small and complete library, but also needs ecology.Just like SQLITE and MongoDB, they have GUI , practice projects , driver and so on. 
At present, I have developed a novel coronavirus health code collector using cloverDB ，and it is being applied in small communities in China ，served a lot of people.
I am very interested in contributing hands-on projects related to the awesome clover library to be developed, such as GUI and development examples, more complete hands-on tutorials and drivers. I will be the first to contribute to the project, and project-related maintenance is upgraded with the CloverDB upgrades. 
Creating new ecological power, the clover will get better and better.

**Comment by ostafen** [comment]
Hi, ASWLaunchs. This sounds a good idea. What project are are you thinking about to start?

**Comment by ASWLaunchs** [comment]
> 

I will submit a small project for epidemic code collection in my repository and then edit the document setting link in your awesome readme. Md. After that, I plan to develop a GUI for cloverDB so that other developers can see the database data visually, just like SQLite also has third-party guis and VSCODE Plugin preview.

**Comment by ostafen** [comment]
Okay, thank you. When you start some project, let me know, I will contribute, and gradually, we will enlarge the clover ecosystem :)

**Comment by ASWLaunchs** [comment]
> Hi, ASWLaunchs. This sounds a good idea. What project are are you thinking about to start? Since this is an embedded library, what do you mean by driver?

driver like [go-sqlite3](https://github.com/mattn/go-sqlite3) , if other program language calls the CloverDB ,then need a driver.

**Comment by ASWLaunchs** [comment]
> Okay, thank you. When you start some project, let me know, I will contribute, and gradually, we will enlarge the clover ecosystem :)

okay , no problem.

**Comment by ostafen** [comment]
@ASWLaunchs Is your coronavirus health code collector an opensource project or a private one?

**Comment by ASWLaunchs** [comment]
> @ASWLaunchs Is your coronavirus health code collector an opensource project or a private one?

opensource project

**Comment by ASWLaunchs** [comment]
Every project I submit is open source and avoids the commercial risk of other developers using it.

**Comment by ostafen** [comment]
Can you link the repo here? I want to give a look at it, and maybe I can also contribute :=)

**Comment by ASWLaunchs** [comment]
> Can you link the repo here? I want to give a look at it, and maybe I can also contribute (or other people interested at it) :=)

okay ,CloverDB is used to store data，80% of the development is now complete . It will be updated before 13th of this month. I haven't uploaded it yet .

**Comment by ASWLaunchs** [comment]
> Can you link the repo here? I want to give a look at it, and maybe I can also contribute (or other people interested at it) :=)

it's ok, https://github.com/ASWLaunchs/healthSentinel
Temporarily completed, but not ideal, some basic functions are not written, but it can solve the problem of uploading pictures and numbering, it has been serviced for my community， mainly used to collect China's epidemic health code picture. Data is stored and read based on CloverDB.
I have been a little busy in the last 10 days. After 24th, I will repair this simple demo and prepare for a database administration tool for the CloverDB. I want to create a GUI with wails. How do you think this idea?

**Comment by ASWLaunchs** [comment]
I always pay attention to the cloverDB API change, and I will invite CloverDB contributors to participate in the development of cloverDB  administration tool. I will invite everyone, if everyone is willing.

**Comment by ostafen** [comment]
Thank you, your contribution is welcome :)
I will also check your project, and try to contribute :)

**Comment by ostafen** [comment]
@ASWLaunchs, any update about the GUI project?
I'm looking forward to see it :=)

**Comment by ostafen** [comment]
I think this should go to Discussion section, so I'll close this

**Comment by ASWLaunchs** [comment]
> I think this should go to Discussion section, so I'll close this

no problem , let's meet in the discussion.
