### ISSUE TITLE
Fixed TestPagedQueryUsingIndex failure

### ISSUE THREAD

**Issue by ahossameldin** [ostafen/clover#156]
The test TestPagedQueryUsingIndex in db_test was failing because it was returning a different number of documents after paging compared to the number of documents inserted. Upon investigation, the issue was caused by duplicate timestamps being set during document insertion, which affected the pagination results.

The time.Now() function was used to set the timestamp for each document, but the insertion process was too fast, causing multiple documents to have the same timestamp. This led to duplicate timestamps, which caused inconsistent results during paging.

To fix this, I made the timestamps unique by adding a small increment to the time.Now() value using nanoseconds. This ensures that each document gets a unique timestamp, even when inserted rapidly.

```
n := 10003
for i := 0; i < n; i++ {
    doc := d.NewDocument()

    // Old code that caused duplicates:
    // doc.Set("timestamp", time.Now()) // this will cause duplicates 

    // New code to ensure unique timestamps:
    doc.Set("timestamp", time.Now().Add(time.Duration(i) * time.Nanosecond)) // this will make it unique

    // Rest of insertion logic...
}
```

**Comment by ostafen** [comment]
Hi, @ahmed-hossam28, could you also submit a PR with the fix?

**Comment by ahossameldin** [comment]
Hi,@ostafen , thanks for your response, i did submit PR a moment ago
