### ISSUE TITLE
Implement regex expression matching

### ISSUE THREAD

**Issue by ostafen** [ostafen/clover#19]
It would be nice to implement a "Like(regex string) " criteria for regex expression matching

**Comment by ASWLaunchs** [comment]
This is a good way, I am watching the CloverDB source code, trying to understand the logic behind it, if I can read the logic of CloverDB, I think I should contribute, do you have any reading of the source code to share it?

**Comment by ostafen** [comment]
Hi, ASWLaunchs. Unfortunately, there is no reading of the source code, currently.
However, the code base is very small, and you only have to understand the relationship between Query and Criteria objects.
No need to understand details of the StorageEngine.
In the context of this issue, what you should do is to simply add a `Like()` function to the **field** struct returning a new Criteria with the new logic. 
However, if you have questions, I could give you further explanations in private (maybe using some chat system)

**Comment by ASWLaunchs** [comment]
> 

Ok, I'll try to do that

**Comment by ostafen** [comment]
Briefly, the Where functions takes a Criteria objects to do filtration on documents. A Criteria is simply a wrapper for a predicate function over a document. This is a function which takes a document and returns true whether the document matches the Criteria. 
In this case, the predicate function to be implemented should return true only if the document contains the given field and it also matches the regular expression passed to Like.

**Comment by ASWLaunchs** [comment]
> Briefly, the Where functions takes a Criteria object to do filtration on documents. A Criteria is simply a wrapper for a predicate function over a document. This is a function which takes a document and returns true if and only if the document matches the Criteria. In this case, the predicate function to be implemented should return true only if the document contains the given field and it also matches the regular expression passed to Like. I hope this brief explanation can be of help

I learned, I will try to make a regex match refer to FindAll() , if there is a progress, I will inform you.
