### ISSUE TITLE
Improve existing documentation

### ISSUE THREAD

**Issue by ostafen** [ostafen/clover#20]
Several additions and functions have been added for the v1.1.0 release. It is important to improve the structure of existing documentation, also adding missing sections.

**Comment by ostafen** [comment]
Last commit (3dbb312075d40e986d8c0319cbe337614a112258) added a more curated documentation in the README.
I will leave this issue open for a while, in order to collect further suggestions.

**Comment by jsgm** [comment]
Now the documentation feels much better. I'll wait until the v1.1.0 is released for translating so we can change as many things we need.

For future versions greater than v1.1.0, once the library is more stable we could create a gitbook -or any other similar tool-, or simply a website and export the documentation there from the git repository.

Also just a minor detail, I use the dark version of Github and I can't see the logo

**Comment by ostafen** [comment]
> Also just a minor detail, I use the dark version of Github and I can't see the logo

Do you refer to the "clover" black part of the logo title?

**Comment by jsgm** [comment]
> > Also just a minor detail, I use the dark version of Github and I can't see the logo
> 
> If you refer to the "clover" black part of the logo title, I'm aware of this issue. But I don't find any color which is suitable both for dark and normal version

Found a way to fix it. Please check the PR: https://github.com/ostafen/clover/pull/21
