### ISSUE TITLE
Add code examples

### ISSUE THREAD

**Issue by ostafen** [ostafen/clover#27]
Hi, all! In order to help new users getting started with clover quickly, it would be good to add an examples folder containing 
several basic code samples showing the main feature of the library

**Comment by jsgm** [comment]
Hello @ostafen,

In my opinion, a good way to organise the examples would be as following:
- **examples**
  - **collections:** Basic examples of creating and deleting collections.
  - **insert:** Working with different types of inserts using both _NewDocument_ and _NewDocumentOf_.
  - **sort:** A few examples for sorting, integers, UNIX dates, etc.
  - **update & delete:** Handling different types of update for both single and all documents.
  - **import & export:** Examples for the upcoming https://github.com/ostafen/clover/issues/16. 
  - **engines:** How to use the config.go functions & options and choosing different engines.

Inside each folder I would personally add a main.go, ready to copy & paste.

[Here's an example](https://github.com/nats-io/nats.go/tree/main/examples) of how other libraries are handling this

**Comment by ostafen** [comment]
I agree with your suggestion!

**Comment by EdwinWalela** [comment]
Hello @ostafen, I would like to take this up. I'm planning on using the structure @jsgm has proposed of having each in its own folder, ready to copy & paste.

**Comment by ostafen** [comment]
Hi, @EdwinWalela, first of all thanks for your interest. Yes, you can use the structure proposed by jsgm :=)
I assigned this to you
