### ISSUE TITLE
Add a db.GetCollections() method

### ISSUE THREAD

**Issue by jsgm** [ostafen/clover#29]
Hello all.

In some cases, specially for old projects it would be interesting to add a `GetCollections()` method that returns a slice of strings with the different existing collections names.

**Comment by ostafen** [comment]
Hi, this is something I was planning. You anticipated me :=)

**Comment by jsgm** [comment]
`ListCollections()` looks fine for me 😄

**Comment by ostafen** [comment]
Since, this is very simple to implement, I will leave the issue open for a while before implementing, to allow new contributors to join

**Comment by DaniloMarques1** [comment]
Hello.

I would like to work on it
