### ISSUE TITLE
SaveOrUpdate

### ISSUE THREAD

**Issue by dbgjerez** [ostafen/clover#34]
https://github.com/ostafen/clover/blob/530c209b547f9df30a159d385a6ec4db7fc7190b/db.go#L63

Hi, 

I'm not sure if this is an issue or discussion. I'm very happy with this database and I like to help it if I can.

Some databases have a function to update or save a new document. In this case, the database is always creating a new document.

I think that if the document ID is provided by the user, it is easier to omit this line and update the document.

What do you think about?, if you are agreed, I can modify it or create a new function and I will do a PR.

Thanks a lot

**Comment by ostafen** [comment]
Hi, @dbgjerez, thank you for your suggestion. I agree with this feature, and your contribution would be welcome.
I think it is better to call the new function `Save()` instead of `SaveOrUpdate()`.

**Comment by dbgjerez** [comment]
Hi, ok I will call it Save(). 
I have just joined the gitter channel ;)
Thanks!
