### ISSUE TITLE
Add a Contains criteria

### ISSUE THREAD

**Issue by ostafen** [ostafen/clover#44]
Hi, all! It could be useful to implement a `Contains(elems ...interface{})` to check if a slice field contains one or more elements.
For example, assume to run the following query

```go
db.Query("myCollection").Where(c.Field("myField").Contains(4)) 
```

on a `myCollection" collection which consists of the following three documents:

```json
{
   ...,
   "myField": [1,2,4]
},
{
   ...,
   "myField": [5,6,7]
},
{
   ...,
   "myField": [4, 10, 20]
}
```

The query would return only the first and the third document.

**Comment by kastolars** [comment]
Hi! I'd like to give this a shot. Just for clarification, what field types (elems) should this function support? I see `int` in the example and `interface` in the signature.

**Comment by ostafen** [comment]
The signature of every criteria usually contains interface{}, so that any type can be supported.
Give a look, for example, at the **Eq** criteria.
You can use reflect.DeepEqual() to perform comparison of interface{}

**Comment by kastolars** [comment]
Okay cool. Should  the function go in `criteria.go` , and the unit test in `db_test.go` ?

**Comment by kastolars** [comment]
In the `Contains` function, can I assume the `docValue` in `docValue := doc.Get(f.name)` (similar to the `In` function) is of type slice, or maybe should it panic in the instance where it isn't a slice? Or maybe fall back to using the `In` function? What do you think?

**Comment by ostafen** [comment]
You should use a type assertion to first check if it is a slice. In the case the field is not a slice, the criteria in not satisfied and you can return false.
