### ISSUE TITLE
Add support for criteria involving operations between fields

### ISSUE THREAD

**Issue by ostafen** [ostafen/clover#49]
Currently, clover db only supports building criteria where you compare a field with a value, like the one in the following example:

```go
db.Query("myCollection").Where(c.Field("myField").Eq(1))
```

Naturally, there are several contexts where one may need to express condition where you compare fields of the same document. For example you may want to select documents satisfying a condition such as `myField1 > myField2`.

This could be integrated inside clover in the following way:
```go
db.Query("myCollection").Where(c.Field("myField1").Gt("$myField2"))
```
where the special syntax `$myField2` tells clover to extract the value to use for comparison from the document field named `myField2`.

Suggestions and feedback about alternative ways to accomplish this are welcome :=)

**Comment by segfault99** [comment]
Nice idea.
I think this syntax explains the intent better and also makes it easier to implement. (no need to check for special character)
```go
db.Query("myCollection").Where(c.Field("myField1").Gt(c.Field("myField2"))
```

**Comment by ostafen** [comment]
Yes, it is the best alternative :)
