### ISSUE TITLE
Inserts do not set up index correctly

### ISSUE THREAD

**Issue by xxxserxxx** [ostafen/clover#6]
This issue was in the pre-badger code (<= dc5b9e3503ecba809eff2436d1ee69a4b171f36b). I'm putting it here for anyone else who wants to continue using the old storage.  Note that if you're doing this, you should also cherry-pick the other indexing bug fix, e736362eb15e75437a1404458148678902a022d4.

The behavior is that `Insert()` of documents after the first would result in an incorrect index; attempts to access those documents would always get the *first* document, but since the code fetched the data based on offset+size, it was always offset(document #1) + size(document # N). This usually resulted in bad JSON formatting errors, either unexpected end of JSON or invalid syntax. The patch is:

```
diff --git a/storage.go b/storage.go
--- a/storage.go
+++ b/storage.go
@@ -260,7 +260,7 @@ func (s *storageImpl) Insert(collection
                return err
        }

-       pointers, err := appendDocs(&collectionFile{File: tempFile, size: 0}, docs)
+       pointers, err := appendDocs(&collectionFile{File: tempFile, size: coll.file.size}, docs)
        if err != nil {
                return err
        }
```

@ostafen, I'm submitting and then closing; hopefully others searching for a fix will find this.

**Comment by ostafen** [comment]
Thank you for pointing this out :+1:
