### ISSUE TITLE
Implement an in-memory storage engine

### ISSUE THREAD

**Issue by ostafen** [ostafen/clover#9]
The persistence layer of CloverDB is abstracted by the StorageEngine interface. The default implementation persists data on disk only and makes use of the badger kv-store. 
It would be useful to also add an alternative StorageEngine implementation running completely in-memory, arranging documents in a map.

**Comment by segfault99** [comment]
Hi, i was considering to implement this but then i remembered that badger also has an in-memory mode. Is there a particular reason not to use it ?

**Comment by ostafen** [comment]
Hi, @segfault99, first of all thank you for the interest, your question is more than legitimate :=) I should have clarified this point in the issue description.

As you claim, it is true that badger has an in memory store, however this would make the library tightly coupled with badger.
If in the future, we may need to switch to an alternative kv store for some reason, then you would also lose the in-memory storage engine.
Moreover, in the future, I plan to structure the library so that if you only want to use clover in-memory, you will not download the badger dependency.
Do you agree with these points?

**Comment by segfault99** [comment]
Thanks for clarifying. Yes i agree, the reason i have guessed was that too. I can work on this one.

**Comment by ostafen** [comment]
Good :=) I assigned this to you. For any doubt, feel free to contact me
