### ISSUE TITLE
Feature: a cmdline tool to explore a cloverDB

### ISSUE THREAD

**Issue by matwachich** [ostafen/clover#96]
Hello, and thanks for this excellent lib!

The title says it all: is there a cmdline tool to explore a cloverDB? Query collections and documents, insert, delete, create indexes...

If not, is it planned?

Thanks :)

**Comment by ostafen** [comment]
Hi, @matwachich, currently it is not in my plans. But if you would like building one, I would certainly collaborate to the project :=)
